version: '3.5'

services:
  django:
    build: .
    user: app
    command: runserver 0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    tmpfs:
      - /tmp
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
      PYTHONDONTWRITEBYTECODE: 'x'
      PYTHONWARNINGS: default
      DEBUG: 'True'
    networks:
      default:
        aliases:
          - testcase
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:
    image: postgres:9.6.10-alpine
    user: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASS: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      default:
        aliases:
          - testcase-db

volumes:
  db_data: {}
