# Generated by Django 2.2.3 on 2020-11-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote', to='wallets.DigitalWallet', verbose_name='Remote account')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='wallets.DigitalWallet', verbose_name='Account')),
            ],
        ),
    ]
